// Font Awesome Configuration
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

import {
  faTrashCan,
  faUser,
  faBars,
  faEdit,
  faEye,
  faLock,
  faGlobe,
  faPlus,
  faAddressBook,
  faSearch,
  faCalculator,
  faArrowRight,
  faArrowLeft,
  faFolder,
  faDoorOpen,
  faCube,
  faRulerCombined,
  faSave,
  faInfoCircle,
  faUndo,
  faChevronDown,
  faShoppingCart,
  faTimes,
  faCheckCircle,
  faTimesCircle,
  faExclamationTriangle,
  faBell,
} from '@fortawesome/free-solid-svg-icons'
import { faGithub } from '@fortawesome/free-brands-svg-icons'

library.add(
  faTrashCan,
  faUser,
  faBars,
  faEdit,
  faEye,
  faLock,
  faGlobe,
  faPlus,
  faAddressBook,
  faSearch,
  faCalculator,
  faArrowRight,
  faArrowLeft,
  faFolder,
  faDoorOpen,
  faCube,
  faRulerCombined,
  faSave,
  faInfoCircle,
  faUndo,
  faChevronDown,
  faShoppingCart,
  faTimes,
  faCheckCircle,
  faTimesCircle,
  faExclamationTriangle,
  faBell,
  faGithub,
)
export { FontAwesomeIcon }
